###############################################
# DOMINIOS Y CERTIFICADOS
###############################################
portainer_domain: "portainer.victor-m.duckdns.org"
npm_domain: "npm.victor-m.duckdns.org"

cert_email: "Victor-jh@outlook.es"

###############################################
# DUCKDNS
###############################################
duckdns_token: "c45cd649-e3ee-4f55-8cc9-af9a5d463a96"
duckdns_subdomain: "victor-m"

###############################################
# PORTAINER
###############################################
portainer_url: "https://portainer.victor-m.duckdns.org"
portainer_username: "Deploy"
portainer_password: "DokttrDpl&dkik51"

###############################################
# PORTAINER - GIT AUTO DEPLOY
###############################################
git_repo_url: "https://github.com/VictorMjh/Proyecto-Dokete.git"
git_branch: "main"
git_compose_path: "docker/portainer"

###############################################
# NGINX PROXY MANAGER
###############################################
npm_url: "http://localhost:81"   # Acceso interno desde el host
npm_username: "Victor-jh@outlook.es"
npm_password: "NPM&dktp5125"
