---
# Defaults para role docker

docker_apt_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_install_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin