---
- name: Crear volumen Portainer
  community.docker.docker_volume:
    name: portainer_data

- name: Crear contenedor Portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    restart_policy: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
