---
- name: Despliegue completo Doketer
  hosts: doketer
  become: yes
  gather_facts: yes

  roles:
    - docker
    #- duckdns
    #- watchtower
    - portainer
    - portainer_git
    - ufw
    - npm