---
- name: Desplegar contenedor Watchtower
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    state: started
    restart_policy: unless-stopped
    command: "--cleanup --schedule '{{ watchtower_schedule }}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock