name: Script Install Docker
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Esta es la máquina donde se ejecuta el job
    steps:
      - name: Check out the code
        uses: actions/checkout@v3  # Clona el código fuente del repositorio

      #- name: Copy deployment files
      #  run: |
      #    scp -P 22 -o StrictHostKeyChecking=no -r ./docker/* deploy@${{ vars.DOKETER_HOST }}:/home/deploy/proyecto-dokete

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usa el secreto SSH creado

      - name: Connect with deply user to Ubuntu Server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p 5122 deploy@${{ vars.DOKETER_HOST }} 'bash -s' <  ./docker/Script-DeployDocker.sh
          
