---
- name: Actualizar cache apt
  apt:
    update_cache: yes
    cache_valid_time: 3600


- name: Instalar dependencias APT
  apt:
    name: "{{ docker_apt_packages }}"
    state: present


- name: A침adir clave GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: A침adir repo de Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present


- name: Instalar Docker Engine
  apt:
    name: "{{ docker_install_packages }}"
    state: present
    update_cache: yes


- name: Asegurar que docker service est치 activo
  service:
    name: docker
    state: started
    enabled: yes


- name: A침adir usuario '{{ ansible_user }}' al grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes